# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency
# To disable this, add this line:
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Set the correct path to your Flutter SDK
flutter_application_path = File.expand_path('C:/src/flutter', __dir__)
load File.join(flutter_application_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'RunnerTests' do
  inherit! :search_paths
  # Pods for testing
end
