name: Flutter iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter with a specific version
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'  # Set to your Flutter version (which includes Dart 3.3.3+)

      # Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build the iOS app (this step generates the iOS project files including Podfile)
      - name: Build iOS dependencies
        run: flutter build ios --no-codesign

      # Install CocoaPods (required for iOS dependencies)
      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      # Build the iOS app for release
      - name: Build iOS release
        run: flutter build ios --release --no-codesign

      # Upload the build artifacts
      - name: Upload iOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos/*.app
